### ISSUE TITLE
edgeware block explore https://scaner.io

### ISSUE THREAD

**Issue by toxotguo** [hicommonwealth/edgeware-node#109]
I built the world's first edgeware block explore https://scaner.io for edgeware. Can view account information, block information, transaction information, etc. May be useful to the community.If you have the hope to add a feature, please contact me.

**Comment by raykyri** [comment]
Awesome!

We'll send out an email to the regular lists when mainnet goes live. It would be great to get this hooked up. In the meantime, FYI, the testnet nodes (testnet1-8) have been updated to serve testnet v0.9.
