### ISSUE TITLE
Couldn't build on Amazon Linux

### ISSUE THREAD

**Issue by cathylong** [hicommonwealth/edgeware-node#112]
When I use the command 'cargo build --release" to build the node, I got below error:
 Compiling wasmi-validation v0.1.0
error[E0432]: unresolved import `hashbrown`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-validation-0.1.0/src/lib.rs:31:5
   |
31 | use hashbrown::HashSet;
   |     ^^^^^^^^^ use of undeclared type or module `hashbrown`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `wasmi-validation`.

To learn more, run the command again with --verbose.

-------------------------
under my /root/.cargo/registry/src/github.com-1ecc6299db9ec823, there are two version of wasmi-validation, 0.1.0 and 0.2.0. 0.2.0 was built successfully.

vim Cargo.toml

[package]
edition = "2018"
name = "wasmi-validation"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Wasm code validator"
license = "MIT/Apache-2.0"
repository = "https://github.com/paritytech/wasmi"
[dependencies.hashbrown]
version = "0.1.8"
optional = true

[dependencies.parity-wasm]
version = "0.31"
default-features = false
[dev-dependencies.assert_matches]
version = "1.1"

[features]
core = ["hashbrown/nightly"]
default = ["std"]
std = ["parity-wasm/std"]

in lib.rs

#[cfg(not(feature = "std"))]
use hashbrown::HashSet;
#[cfg(feature = "std")]
use std::collections::HashSet;

and in the same directory, hashbrown-0.1.8 exists. How can I fix this issue?

**Comment by raykyri** [comment]
Hi Cathy,

This should be fixed in the latest `master` -- let me know if you still have any issues.

**Comment by cathylong** [comment]
Hello Raymond,
I switched the Linux system to ubuntu, this issue was fixed. but now I have another issue, in the last step, compiling process edgeware fails, could you help check it? thank you very much!
error: Could not compile `edgeware`.
​
Caused by:​
  process didn't exit successfully: `rustc --edition=2018 --crate-name edgeware node/src/main.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=812ac87ec400ab1a -C extra-filename=-812ac87ec400ab1a --out-dir /home/ubuntu/edgeware-node/target/release/deps -L dependency=/home/ubuntu/edgeware-node/target/release/deps --extern ctrlc=/home/ubuntu/edgeware-node/target/release/deps/libctrlc-93029e8961772e51.rlib --extern edgeware_cli=/home/ubuntu/edgeware-node/target/release/deps/libedgeware_cli-8553da328c637562.rlib --extern error_chain=/home/ubuntu/edgeware-node/target/release/deps/liberror_chain-f426d7329aefe7db.rlib --extern futures=/home/ubuntu/edgeware-node/target/release/deps/libfutures-d77435167a4ccdbe.rlib -L native=/home/ubuntu/edgeware-node/target/release/build/clear_on_drop-fa99d4bd8ea2d911/out -L native=/home/ubuntu/edgeware-node/target/release/build/backtrace-sys-5107fc534a07c856/out -L native=/home/ubuntu/edgeware-node/target/release/build/ring-aaf1df05e595417c/out -L native=/home/ubuntu/edgeware-node/target/release/build/libz-sys-3b0126c85848861c/out/build -L native=/home/ubuntu/edgeware-node/target/release/build/librocksdb-sys-895374a80e50f313/out -L native=/home/ubuntu/edgeware-node/target/release/build/librocksdb-sys-895374a80e50f313/out -L native=/home/ubuntu/edgeware-node/target/release/build/librocksdb-sys-895374a80e50f313/out -L native=/home/ubuntu/edgeware-node/target/release/build/librocksdb-sys-895374a80e50f313/out -L native=/home/ubuntu/edgeware-node/target/release/build/librocksdb-sys-895374a80e50f313/out -L native=/home/ubuntu/edgeware-node/target/release/build/librocksdb-sys-895374a80e50f313/out` (signal: 9, SIGKILL: kill)​


-Cathy
________________________________
发件人: Raymond Zhong <notifications@github.com>
发送时间: 2019年10月5日 1:38
收件人: hicommonwealth/edgeware-node <edgeware-node@noreply.github.com>
抄送: cathylong <xuyier@msn.com>; Author <author@noreply.github.com>
主题: Re: [hicommonwealth/edgeware-node] Couldn't build on Amazon Linux (#112)


Hi Cathy,

This should be fixed in the latest master -- let me know if you still have any issues.
