### ISSUE TITLE
node stop sync = hash not equal

### ISSUE THREAD

**Issue by iammelea** [hicommonwealth/edgeware-node#113]
./target/release/edgeware --version
edgeware 1.0.0-a02705e-x86_64-linux-gnu 

node stop sync = hash not equal
this msg in the buckle.

![Screenshot from 2019-10-08 15-11-16](https://user-images.githubusercontent.com/38863192/66400935-a7497280-e9e2-11e9-87d9-8295a2436e51.png)

**Comment by raykyri** [comment]
It might be the case that `scripts/purge-chain.sh` isn't working correctly. Maybe `rm -rf ~/.local/share/edgeware/chains/*` will fix this?
