### ISSUE TITLE
faucet is not work！

### ISSUE THREAD

**Issue by xihucuyu888** [hicommonwealth/edgeware-node#143]
can somebody send me some testnet EDG ? 
my address： 5Hq28zRrM6SiVsiP4XGtYh7UHeBYCihP9M7s5C4BF42GgovX
i can't not fetch testnet EDG from faucet successfully

**Comment by ben-staked** [comment]
@xihucuyu888 Sent some tEDG your way.  Can this issue be closed?

**Comment by drewstone** [comment]
I think @thomivy is working to get the Faucet working with the new testnet too! Thanks @ben-staked
