### ISSUE TITLE
edgeware-node version is v1.0.2, Compile failed

### ISSUE THREAD

**Issue by gitcodeporter** [hicommonwealth/edgeware-node#144]
Compiling enumflags2_derive v0.6.2
   Compiling wasm-bindgen-macro v0.2.58
   Compiling paste-impl v0.1.6
   Compiling futures-macro v0.3.4
   Compiling const-random-macro v0.1.8
   Compiling web-sys v0.3.35
   Compiling sp-storage v2.0.0 (https://github.com/paritytech/substrate.git#00a400f8)
   Compiling enumflags2 v0.6.2
   Compiling paste v0.1.6
   Compiling const-random v0.1.8
   Compiling js-sys v0.3.35
   Compiling ahash v0.2.18
error[E0603]: struct `Memory` is private
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.35/src/lib.rs:4873:60
     |
4873 |                 let mem = buf.unchecked_ref::<WebAssembly::Memory>();
     |                                                            ^^^^^^ this struct is private
     |
note: the struct `Memory` is defined here
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.35/src/lib.rs:3516:5
     |
3516 |     #[wasm_bindgen]
     |     ^^^^^^^^^^^^^^^
     = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0603]: struct `Memory` is private
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.35/src/lib.rs:4898:60
     |
4898 |                 let mem = buf.unchecked_ref::<WebAssembly::Memory>();
     |                                                            ^^^^^^ this struct is private
     |
note: the struct `Memory` is defined here
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.35/src/lib.rs:3516:5
     |
3516 |     #[wasm_bindgen]
     |     ^^^^^^^^^^^^^^^
     = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0603]: struct `Memory` is private
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.35/src/lib.rs:4908:60
     |
4908 |                 let mem = buf.unchecked_ref::<WebAssembly::Memory>();
     |                                                            ^^^^^^ this struct is private
     |
note: the struct `Memory` is defined here
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.35/src/lib.rs:3516:5
     |
3516 |     #[wasm_bindgen]
     |     ^^^^^^^^^^^^^^^
     = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0603`.
error: could not compile `js-sys`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

warning: build failed, waiting for other jobs to finish...
error: build failed

**edgeware-node version is v1.0.2**

**Comment by drewstone** [comment]
What version rust are you using? Have you updated your rust versions?

**Comment by gitcodeporter** [comment]
rust version is 1.41.0
