### ISSUE TITLE
api.query.system.events.at

### ISSUE THREAD

**Issue by xihucuyu888** [hicommonwealth/edgeware-node#145]
i tried this api on the mainnet:

**const events = await api.query.system.events.at('0xf3bb6f5071dceffb0e65b946accf790e2473a6e5bd5925b514b3bfda41229b5c')**

and got some error:

Error: getStorage(key: StorageKey, at?: BlockHash): StorageData:: -32603: Unknown error occured: Client(UnknownBlock("State alread
    at e.selector (https://polkadot.js.org/apps/main.7338ea85.js:65:328398)
    at e.error (https://polkadot.js.org/apps/vendor.5d68bb2b.js:1:57594)
    at e._error (https://polkadot.js.org/apps/vendor.5d68bb2b.js:1:1357)
    at e.error (https://polkadot.js.org/apps/vendor.5d68bb2b.js:1:1051)
    at e.notifyError (https://polkadot.js.org/apps/vendor.5d68bb2b.js:1:5903)
    at e._error (https://polkadot.js.org/apps/vendor.5d68bb2b.js:8:22446)
    at e.error (https://polkadot.js.org/apps/vendor.5d68bb2b.js:1:1051)
    at e.notifyError (https://polkadot.js.org/apps/vendor.5d68bb2b.js:1:5903)
    at e._error (https://polkadot.js.org/apps/vendor.5d68bb2b.js:8:22446)
    at e.error (https://polkadot.js.org/apps/vendor.5d68bb2b.js:1:1051)

it seems that some blocks  would generate the error above,   other blocks are ok

**Comment by drewstone** [comment]
You may need to be connected to any archive node. This could be thrown potentially from a client that has already pruned blocks at that height.

**Comment by xihucuyu888** [comment]
> You may need to be connected to any archive node. This could be thrown potentially from a client that has already pruned blocks at that height.

do you mean that I should start the edgeware node using params like this:
--pruning archive

**Comment by nblogist** [comment]
@drewstone I am running the node in archival mode (using: .**/target/release/edgeware --chain=geware --execution-syncicing wasm --pruning=archive**  ), yet this line gives the following error:
 
**const events = await api.query.system.events.at('0xf3bb6f5071dceffb0e65b946accf790e2473a6e5bd5925b514b3bfda41229b5c')**

```
RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: -32603: Unknown error occured: Client(UnknownBlock("State already discarded for BlockId::Hash(0xf3bb6f5071dceffb0e65b946accf790e247
Error: -32603: Unknown error occured: Client(UnknownBlock("State already discarded for BlockId::Hash(0xf3bb6f5071dceffb0e65b946accf790e247
```
Do I have to keep running the node for some time?

**Comment by nblogist** [comment]
@drewstone  After running the node in archival mode (using: ./target/release/edgeware --chain=edgeware --execution-syncing wasm --pruning=archive ) and letting _it run overnight_ for the following line:

**const events = await api.query.system.events.at('0xf3bb6f5071dceffb0e65b946accf790e2473a6e5bd5925b514b3bfda41229b5c')**

I am getting this error
```
Unable to decode storage system.events: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0x959f/[149,159]
RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0x959f/[149,159]
Error: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0x959f/[149,159]
```

**Comment by drewstone** [comment]
How are you initializing the api?

**Comment by nblogist** [comment]
Like So:
  const wsProvider = new WsProvider('ws://127.0.0.1:9944');
  const api = await ApiPromise.create({ provider: wsProvider });

**Comment by drewstone** [comment]
You need to use the Edgeware types as well when you initialize the API. You can find them here: https://github.com/hicommonwealth/edgeware-node-types
