### ISSUE TITLE
transaction fee

### ISSUE THREAD

**Issue by gitcodeporter** [hicommonwealth/edgeware-node#146]
As for the transaction fee of EDG's main network, the official information does not mention the transaction fee. I want to know how to calculate the transaction fee

**Comment by ltfschoen** [comment]
Edgeware is based on Substrate. The Substrate documentation explains how to calculate Transaction Fees here https://substrate.dev/docs/en/knowledgebase/runtime/fees#fee-calculation, whilst how to calculate Polkadot's Transaction Fees are mentioned here https://wiki.polkadot.network/docs/en/learn-transaction-fees.

So you'd use the configurable parameters that are defined in Edgeware's runtime https://github.com/hicommonwealth/edgeware-node/blob/master/node/runtime/edgeware/src/lib.rs to calculate the final transaction fee. Note that some of those configurable parameters may not be in the runtime until Edgeware's runtime is upgraded to a more recent Substrate release https://github.com/paritytech/substrate/releases
