### ISSUE TITLE
How to generate the address of EDG main network account

### ISSUE THREAD

**Issue by gitcodeporter** [hicommonwealth/edgeware-node#147]
How to generate the address of EDG main network account, such as msmry7ypw8uth2cc533jfcatwovplcnefyvs2b9dparufzo

`const keyring = new Keyring({ type: 'sr25519' });
    const keyringPair = keyring.addFromMnemonic(‘123456’);
    console.log(keyringPair.publicKey)
    console.log(keyringPair.address)`
like this?

**Comment by drewstone** [comment]
The data you mention is the address.

You need to configure the keyring with the Edgeware network ID which is 7 and then you would wan to grab the `.address` contents. Also you'll need to enter a valid mnemonic.

You can similarly use `subkey`. After downloading you can run `subkey -n edgeware generate` to generate a keypair.

**Comment by gitcodeporter** [comment]
How to generate a pair of keypairs using nodejs? And how to configure the Keyring with the edgeware network ID which is 7

**Comment by gitcodeporter** [comment]
Waiting for your reply Online

**Comment by raykyri** [comment]
Hey @gitcodeporter, this code might be helpful for you: https://github.com/hicommonwealth/edgeware-keygen/blob/master/client/app.js

It's also hosted online here: https://edgewa.re/keygen/

**Comment by gitcodeporter** [comment]
thank you
