### ISSUE TITLE
Thread 'main' panicked at 'Error opening spec file: No such file or directory

### ISSUE THREAD

**Issue by rzup** [hicommonwealth/edgeware-node#155]
Hi, I encountered this error trying to start edgeware node with --name --sentry --chain=edgeware flags. Haven't found any similar errors open.
====================

Version: 3.0.3-7263b49-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   2: std::panicking::begin_panic
   3: edgeware_cli::load_spec
   4: sc_cli::params::shared_params::SharedParams::update_config
   5: sc_cli::commands::runcmd::RunCmd::update_config
   6: edgeware_cli::command::run
   7: edgeware::main
   8: std::rt::lang_start::{{closure}}
   9: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  10: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  11: std::panicking::try
             at src/libstd/panicking.rs:281
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  12: main
  13: __libc_start_main
  14: _start

Thread 'main' panicked at 'Error opening spec file: No such file or directory (os error 2)', node/cli/src/chain_spec.rs:92

This is a bug. Please report it at:

	https://github.com/hicommonwealth/edgeware-node/issues/new

**Comment by drewstone** [comment]
It looks like your command forgot to add a name `--name <NAME_HERE>`. Otherwise I'm not sure since it looks like you are putting the chain in correctly..

Are you downloading from source?

**Comment by rzup** [comment]
That wasn't the problem I ran the command with --name ABC. It had to been something else. Since then  I did the whole installation again and the problem is no longer present.

**Comment by lincolngit** [comment]
I met the some problem too.  How did you solve it before?

**Comment by raykyri** [comment]
This was resolved by changing directory back to the root of the repo, and running using `./target/release/edgeware` instead of `./edgeware` :)
