### ISSUE TITLE
Feature Request: Embed genesis spec in binary

### ISSUE THREAD

**Issue by carumusan** [hicommonwealth/edgeware-node#156]
Currently you specify --chain=edgeware and then it looks for a file in the chains directory. I think a more robust approach would be to embed the specs in the binary. Obviously while still being overridable.

This would solve a lot of the issues that newcomers have with the "Error opening spec file" errors.

**Comment by thomivy** [comment]
Adding this link you shared in Suggestions on a potential method 

https://docs.rs/crate/rust-embed/0.3.5

**Comment by drewstone** [comment]
Yea I'll tackle this with the next update! I think we just need to add the spec files to the `node/cli` directory similar to how `flaming-fir` is.
