### ISSUE TITLE
Upgrading bootnodes IDs from genesis required.

### ISSUE THREAD

**Issue by remzrn** [hicommonwealth/edgeware-node#166]
Upon upgrading my node to the new substrate, a set of warnings of the following kind appear: 
```

'"You are using the peer ID QmVFxV5Ay158YiS7bkxNkAshEECDFMbqnfkizTgEfKQC7F. 
This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. 
Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key"
```

It seems that it is related to the wait the bootnodes are defined in the configuration. Their IDs ought to be updated. I did not find which RPC call could provide me with the node ID, but using subkey inspect-node-key works: you have to perform the following it each of the bootnodes. The private key they are referring to is (by default) located in `.local/share/edgeware/chains/edgeware/network/secret_ed25519`

**Comment by drewstone** [comment]
Thanks, I'll get this done this week!

**Comment by remzrn** [comment]
This should not be something you will experience before you'll get substrate upgraded to a version post 30th of May. I suggest it would be sufficient to publish a list of the updated bootnode addresses to be used with the updated version.
