### ISSUE TITLE
governance: On chain storage of comments may be cumbersome

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/edgeware-node#17]
Clone of: https://github.com/hicommonwealth/edge-governance/issues/2

# Overview

We should look to merkelize the storage of comments for a specific proposal. That is just storing a merkle root for the comments on one proposal then storing the bulk of content on IPFS utilizing PubSub to serve content.

**Comment by 4meta5** [comment]
* Is this still open? 
* How/where is comment storage done now? What is posted on-chain and what is the verification process?

cc @dvc94ch

**Comment by drewstone** [comment]
We aren't storing comments in any modules currently. This was from a former life of edgeware.

**Comment by dvc94ch** [comment]
Merkelizing the storage of comments and putting them on ipfs is the easy part. Most of the work for that we already did with ipfs-embed and tiny-multihash. I still havent gotten around to building a runtime module that allows verifying properties from a merkle dag stored in ipfs, but with a custom multihash code we can make the cid refer to the merkle root. I'll make a demo for this soon.

The hard part is ensuring availability of the ipfs blocks. Do full nodes store them, who pays for the storage, etc. I've not spent much time thinking about this yet, but I'm sure there are solutions.
