### ISSUE TITLE
Unable to support FlappyTips

### ISSUE THREAD

**Issue by ltfschoen** [hicommonwealth/edgeware-node#176]
I've created this game FlappyTips https://flappytips.herokuapp.com/ (only gives you the option to switch between chains when playing on a Desktop computer, since there's a modal bug on Mobile at the moment so it always uses Kusama by default). It currently works on the Kusama 'wss://cc3-5.kusama.network/' and Polkadot CC-1  'wss://cc1-1.polkadot.network' endpoints, and they both use the Treasury runtime module, which allows users to submit their score to the treasury to see if they get a tip.
If you run the app on a Desktop computer, it'll allow you to choose different chains, but if you run it on a Mobile device it only uses Kusama (since there's currently a bug in overlapping modals).

But when I try to enable support for switching to Edgware 'wss://mainnet1.edgewa.re' on Desktop, since it has the Treasury module which is needed, by uncommenting this line in the code https://github.com/ltfschoen/flappytips/blob/master/src/constants/index.js#L12), I get the following error:
<img width="1417" alt="Screenshot 2020-07-05 at 11 25 31 pm" src="https://user-images.githubusercontent.com/6226175/86542562-f3482a00-bf16-11ea-849f-c6bb9a80b598.png">.

I received community feedback requesting a Leaderboard smart contract in ink! 2.0 (smart contract language) here https://github.com/ltfschoen/flappytips/blob/master/ink/contracts/leaderboard/lib.rs, as I want it to be decentralised, and I want to deploy it to Edgeware and integrate it into the game.

The leaderboard contract would need to be funded by treasury and/or community of each chain that wants it in order to pay for storage rent, so it doesn't become tombstoned (that way the leaderboard will only survive as long as it adds value). It's been coded so only the game's contract owner or an owner delegate can update it new scores that players get. For your score to be listed on the leaderboard you'd have to pay a transaction fee to store your score (unless the contract was funded to cover those fees), but if you're lucky enough to received a tip from the treasury it may cover a proportion of that transaction fee. Each month the treasury of each chain may choose to gift the top players on the leaderboard (or those most active).

In Polkadot.js Apps it shows that Edgeware is using the same for the following as Kusama: api v1.23.0-beta.6, apps v0.48.0-beta.18
```
Unable to decode storage system.events: createType(Vec<EventRecord>):: Struct: failed on 'data':: Unable to create Enum via index 20, in Normal, Operational, Mandatory
console.<computed> @ index.js:1
_formatOutput @ index.js:311
(anonymous) @ index.js:185
MapSubscriber._next @ map.ts:85
Subscriber.next @ Subscriber.ts:100
SwitchMapSubscriber.notifyNext @ switchMap.ts:173
InnerSubscriber._next @ InnerSubscriber.ts:18
Subscriber.next @ Subscriber.ts:100
CombineLatestSubscriber.notifyNext @ combineLatest.ts:314
InnerSubscriber._next @ InnerSubscriber.ts:18
Subscriber.next @ Subscriber.ts:100
(anonymous) @ subscribeToPromise.ts:10
Promise.then (async)
(anonymous) @ subscribeToPromise.ts:8
Observable._trySubscribe @ Observable.ts:239
Observable.subscribe @ Observable.ts:218
subscribeToResult @ subscribeToResult.ts:37
CombineLatestSubscriber._complete @ combineLatest.ts:289
Subscriber.complete @ Subscriber.ts:127
(anonymous) @ subscribeToArray.ts:13
Observable._trySubscribe @ Observable.ts:239
Observable.subscribe @ Observable.ts:218
CombineLatestOperator.call @ combineLatest.ts:255
Observable.subscribe @ Observable.ts:215
subscribeToResult @ subscribeToResult.ts:37
SwitchMapSubscriber._innerSub @ switchMap.ts:143
SwitchMapSubscriber._next @ switchMap.ts:129
Subscriber.next @ Subscriber.ts:100
MapSubscriber._next @ map.ts:90
Subscriber.next @ Subscriber.ts:100
(anonymous) @ subscribeToArray.ts:11
Observable._trySubscribe @ Observable.ts:239
Observable.subscribe @ Observable.ts:218
MapOperator.call @ map.ts:60
Observable.subscribe @ Observable.ts:215
SwitchMapOperator.call @ switchMap.ts:102
Observable.subscribe @ Observable.ts:215
MapOperator.call @ map.ts:60
Observable.subscribe @ Observable.ts:215
CatchOperator.call @ catchError.ts:108
Observable.subscribe @ Observable.ts:215
ConnectableObservable.connect @ ConnectableObservable.ts:44
RefCountOperator.call @ refCount.ts:80
Observable.subscribe @ Observable.ts:215
TakeOperator.call @ take.ts:73
Observable.subscribe @ Observable.ts:215
ThrowIfEmptyOperator.call @ throwIfEmpty.ts:50
Observable.subscribe @ Observable.ts:215
(anonymous) @ Observable.ts:361
Observable.toPromise @ Observable.ts:359
(anonymous) @ Api.js:80
(anonymous) @ Game.js:118
async function (async)
(anonymous) @ Game.js:98
(anonymous) @ Api.js:92
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
(anonymous) @ Api.js:92
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:266
SafeSubscriber.next @ Subscriber.ts:208
Subscriber._next @ Subscriber.ts:140
Subscriber.next @ Subscriber.ts:100
TapSubscriber._next @ tap.ts:126
Subscriber.next @ Subscriber.ts:100
Subscriber._next @ Subscriber.ts:140
Subscriber.next @ Subscriber.ts:100
Subject.next @ Subject.ts:71
ReplaySubject.nextInfiniteTimeWindow @ ReplaySubject.ts:53
Subscriber._next @ Subscriber.ts:140
Subscriber.next @ Subscriber.ts:100
DistinctUntilChangedSubscriber._next @ distinctUntilChanged.ts:122
Subscriber.next @ Subscriber.ts:100
Subscriber._next @ Subscriber.ts:140
Subscriber.next @ Subscriber.ts:100
update @ index.js:242
value @ Provider.js:211
value @ Provider.js:146
Show 21 more frames
index.js:1 2020-07-05 23:24:06        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: Struct: failed on 'data':: Unable to create Enum via index 20, in Normal, Operational, Mandatory
console.<computed> @ index.js:1
apply @ logger.js:83
error @ logger.js:118
logErrorMessage @ index.js:61
(anonymous) @ index.js:186
CatchSubscriber.error @ catchError.ts:133
MapSubscriber._next @ map.ts:87
Subscriber.next @ Subscriber.ts:100
SwitchMapSubscriber.notifyNext @ switchMap.ts:173
InnerSubscriber._next @ InnerSubscriber.ts:18
Subscriber.next @ Subscriber.ts:100
CombineLatestSubscriber.notifyNext @ combineLatest.ts:314
InnerSubscriber._next @ InnerSubscriber.ts:18
Subscriber.next @ Subscriber.ts:100
(anonymous) @ subscribeToPromise.ts:10
Promise.then (async)
(anonymous) @ subscribeToPromise.ts:8
Observable._trySubscribe @ Observable.ts:239
Observable.subscribe @ Observable.ts:218
subscribeToResult @ subscribeToResult.ts:37
CombineLatestSubscriber._complete @ combineLatest.ts:289
Subscriber.complete @ Subscriber.ts:127
(anonymous) @ subscribeToArray.ts:13
Observable._trySubscribe @ Observable.ts:239
Observable.subscribe @ Observable.ts:218
CombineLatestOperator.call @ combineLatest.ts:255
Observable.subscribe @ Observable.ts:215
subscribeToResult @ subscribeToResult.ts:37
SwitchMapSubscriber._innerSub @ switchMap.ts:143
SwitchMapSubscriber._next @ switchMap.ts:129
Subscriber.next @ Subscriber.ts:100
MapSubscriber._next @ map.ts:90
Subscriber.next @ Subscriber.ts:100
(anonymous) @ subscribeToArray.ts:11
Observable._trySubscribe @ Observable.ts:239
Observable.subscribe @ Observable.ts:218
MapOperator.call @ map.ts:60
Observable.subscribe @ Observable.ts:215
SwitchMapOperator.call @ switchMap.ts:102
Observable.subscribe @ Observable.ts:215
MapOperator.call @ map.ts:60
Observable.subscribe @ Observable.ts:215
CatchOperator.call @ catchError.ts:108
Observable.subscribe @ Observable.ts:215
ConnectableObservable.connect @ ConnectableObservable.ts:44
RefCountOperator.call @ refCount.ts:80
Observable.subscribe @ Observable.ts:215
TakeOperator.call @ take.ts:73
Observable.subscribe @ Observable.ts:215
ThrowIfEmptyOperator.call @ throwIfEmpty.ts:50
Observable.subscribe @ Observable.ts:215
(anonymous) @ Observable.ts:361
Observable.toPromise @ Observable.ts:359
(anonymous) @ Api.js:80
(anonymous) @ Game.js:118
async function (async)
(anonymous) @ Game.js:98
(anonymous) @ Api.js:92
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
(anonymous) @ Api.js:92
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:266
SafeSubscriber.next @ Subscriber.ts:208
Subscriber._next @ Subscriber.ts:140
Subscriber.next @ Subscriber.ts:100
TapSubscriber._next @ tap.ts:126
Subscriber.next @ Subscriber.ts:100
Subscriber._next @ Subscriber.ts:140
Subscriber.next @ Subscriber.ts:100
Subject.next @ Subject.ts:71
ReplaySubject.nextInfiniteTimeWindow @ ReplaySubject.ts:53
Subscriber._next @ Subscriber.ts:140
Subscriber.next @ Subscriber.ts:100
DistinctUntilChangedSubscriber._next @ distinctUntilChanged.ts:122
Subscriber.next @ Subscriber.ts:100
Subscriber._next @ Subscriber.ts:140
Subscriber.next @ Subscriber.ts:100
update @ index.js:242
value @ Provider.js:211
value @ Provider.js:146
Show 24 more frames
createType.js:69 Uncaught (in promise) Error: createType(Vec<EventRecord>):: Struct: failed on 'data':: Unable to create Enum via index 20, in Normal, Operational, Mandatory
    at createTypeUnsafe (createType.js:69)
    at Rpc._formatStorageData (index.js:343)
    at Rpc._formatOutput (index.js:309)
    at MapSubscriber.project (index.js:185)
    at MapSubscriber._next (map.ts:85)
    at MapSubscriber.Subscriber.next (Subscriber.ts:100)
    at SwitchMapSubscriber.notifyNext (switchMap.ts:173)
    at InnerSubscriber._next (InnerSubscriber.ts:18)
    at InnerSubscriber.Subscriber.next (Subscriber.ts:100)
    at CombineLatestSubscriber.notifyNext (combineLatest.ts:314)
    at InnerSubscriber._next (InnerSubscriber.ts:18)
    at InnerSubscriber.Subscriber.next (Subscriber.ts:100)
    at subscribeToPromise.ts:10
```

**Comment by drewstone** [comment]
@jnaviask and I are looking into this with our types now.

**Comment by ltfschoen** [comment]
i tried adding `edgeware-node-types` here https://github.com/ltfschoen/flappytips/compare/luke/edgeware, but i still get the same error

**Comment by ltfschoen** [comment]
i found that the bug only happens in the code here when calling `api.query.system.events.at(currentBlockHash)` https://github.com/ltfschoen/flappytips/compare/luke/edgeware#diff-18b7ad104d8cfc57b4a21a9afe698b75R175, but i don't need that for the game anyway

**Comment by ltfschoen** [comment]
i tried changing from latest `"edgeware-node-types": "^2.3.3"`, to `"edgeware-node-types": "^2.3.0"`, as suggested, but it still gives the error

**Comment by jnaviask** [comment]
You may need `"2.3.0"` instead of `"^2.3.0"`, because v2.3.3 is still an acceptable match for `"^2.3.0"`.

But I'm also a little confused, because the error you're getting seems like an initialization issue.

**Comment by ltfschoen** [comment]
i create the polkadot API here https://github.com/ltfschoen/flappytips/blob/master/src/Game.js#L91.

i tried changing to `"2.3.0"` in this branch https://github.com/ltfschoen/flappytips/compare/luke/edgeware, but then when i ran `yarn` it gave error:
```
$ yarn run build && yarn run start-dev
yarn run v1.22.4
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/Game.js
Cannot find module: 'edgeware-node-types/interfaces/definitions'. Make sure this package is installed.

You can install this package by running: yarn add edgeware-node-types/interfaces/definitions.
```

Note that because my project isn't using TypeScript, when following the instructions here https://www.npmjs.com/package/edgeware-node-types, I didn't update any tsconfig.json file, and where it says to add code `const types = Object.values(edgewareDefinitions).reduce((res, { types }): object => ({ ...res, ...types }), {});` i instead added `const types = Object.values(edgewareDefinitions).reduce((res, { types }): object => ({ ...res, ...types }), {});` (i.e. without `: object` since i'm not using TypeScript.

**Comment by ltfschoen** [comment]
it was giving that error because in `"2.3.0"` the definitions were in folder `edgeware-node-types/dist/definitions` whereas in the later version `"2.3.3"` the definitions were in the folder `edgeware-node-types/interfaces/definitions`. so i tried updating the code to import from the `dist` folder instead like so:
```
import * as edgewareDefinitions from 'edgeware-node-types/dist/definitions';
```
but still got the error when it ran `api.query.system.events.at(currentBlockHash)`

**Comment by jnaviask** [comment]
You may need to modify the line

```
const types = Object.values(edgewareDefinitions).reduce((res, { types }): object => ({ ...res, ...types }), {});
```

To unwrap defaults, with the earlier version:

```
const types = Object.values(edgewareDefinitions).reduce((res, { default: { types } }) => ({ ...res, ...types }), {});
```

**Comment by ltfschoen** [comment]
I tried making those changes here https://github.com/ltfschoen/flappytips/compare/luke/test-176 (i.e. switching to 2.3.0 where it's located in edgeware-node-types/dist/definitions, and then unwrapping the defaults with the earlier version as you mentioned, and uncommenting the `api.query.system.events.at(currentBlockHash)` code
However I still get the same error.

**Comment by jnaviask** [comment]
What's the steps to run and reproduce?
