### ISSUE TITLE
DRR: TypeError: this._rpcCore.state.queryStorageAt is not a function

### ISSUE THREAD

**Issue by ltfschoen** [hicommonwealth/edgeware-node#180]
When I try to connect to the Berlin Edgeware Testnet and go to https://polkadot.js.org/apps/#/contracts/code to try and upload a smart contract, I get error `DRR: TypeError: this._rpcCore.state.queryStorageAt is not a function` and `API-WS: disconnected from wss://berlin1.edgewa.re code: 1006 reason: ''` in the browser console

**Comment by drewstone** [comment]
Gonna close as Berlin testnet is no longer supported, let me know if you see these issues with the Beresheet testnet!
