### ISSUE TITLE
Uncaught Error: Extrinsic contracts.putCode expects 2 arguments, got 1.

### ISSUE THREAD

**Issue by ltfschoen** [hicommonwealth/edgeware-node#181]
When I try to deploy and instantiate an ink! contract using Edgeware Mainnet I get an error. I first connect to Edgeware Mainnet wss://mainnet1.edgewa.re and go to https://polkadot.js.org/apps/#/contracts/code, then select an account with a balance of EDG, and then drag-and-drop the leaderboard.wasm and metadata.json (ABI) files (which i've stored a temporarily copy of them at https://github.com/ltfschoen/flappytips/tree/master/ink/contracts/leaderboard/backup for the purpose of debugging this issue, even though those files are generated in folder flappytips/ink/contracts/leaderboard/target/ after running `cargo +nightly contract build` and `cargo +nightly contract generate-metadata`), and then click "Upload", it displays the following error in the browser console `Uncaught Error: Extrinsic contracts.putCode expects 2 arguments, got 1.`. But when I view the Polkadot.js API docs https://polkadot.js.org/api/substrate/extrinsics.html#putcode-code-bytes it says that `api.tx.contracts.putCode(code: bytes)` only accepts that single argument. The code of the ink! leaderboard contract is here https://github.com/ltfschoen/flappytips/tree/master/ink/contracts/leaderboard/lib.rs. See screenshot below:
<img width="580" alt="Screenshot 2020-07-08 at 2 45 54 pm" src="https://user-images.githubusercontent.com/6226175/86920985-c2404300-c12a-11ea-9c14-f33a0396f880.png">

**Comment by ltfschoen** [comment]
I received a response in a few Riot messages here: https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$159421736376244cVbCu:matrix.parity.io?via=matrix.parity.io&via=matrix.org&via=web3.foundation

**Comment by drewstone** [comment]
Yep, we are older. The function signature can be found: https://github.com/paritytech/substrate/blob/00a400f82539e2f78e8ddbcd98aea512c87c5f3c/frame/contracts/src/lib.rs#L571
