### ISSUE TITLE
When tried to launch via Systemd following panic happening

### ISSUE THREAD

**Issue by vsatyanaveen** [hicommonwealth/edgeware-node#195]
OS -  Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-112-generic x86_64)
Version TAG - 3.0.1

The edgeware --chain=edgeware command is running fine under non root user but when tried to run as service the following error is appearing. 

Version: 3.0.1-4da8fb1-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:490
   2: std::panicking::begin_panic
   3: edgeware_cli::load_spec
   4: sc_cli::init_config
   5: sc_cli::run
   6: edgeware_cli::command::run
   7: edgeware::main
   8: std::rt::lang_start::{{closure}}
   9: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:297
      std::panicking::try
             at src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  10: main
  11: __libc_start_main
  12: _start

Thread 'main' panicked at 'Error opening spec file: No such file or directory (os error 2)', node/cli/src/chain_spec.rs:92

**Comment by drewstone** [comment]
It seems to not be finding the chain spec, have you resolved this? You just need to ensure the chainspec is stored in the right location for your node.
