### ISSUE TITLE
Docker build failed at 9e444ec564c509d6bd59a6a9c417cffedcf4b050

### ISSUE THREAD

**Issue by yangwao** [hicommonwealth/edgeware-node#207]
I've just did on 9e444ec564c509d6bd59a6a9c417cffedcf4b050

```
docker build .
```

![image](https://user-images.githubusercontent.com/5887929/90110847-2075cc80-dd4e-11ea-9cf9-ccd66cbfd44c.png)

I can lookup on fix later, just noting it down.

**Comment by yangwao** [comment]
Might be related https://github.com/hicommonwealth/edgeware-node/issues/209

**Comment by drewstone** [comment]
So the short fix is to manually edit that file `option-parser.cc` and define a `CMAKE_PROJECT_VERSION` at the top of the file. I think I used `1.0.3`.

For some reason this also only occurred for my on Ubuntu 18.04 nodes.

**Comment by hypnotortoise** [comment]
This is also impacting all builds via Dockerfile, because you're building on `phusion/baseimage:0.11` aka Ubuntu 18.04. After changing to `focal-1.0.0alpha1`, builds are once again successful without modifying the codebase.
