### ISSUE TITLE
Can't run edgeware-mac binary for Beresheet

### ISSUE THREAD

**Issue by yangwao** [hicommonwealth/edgeware-node#208]
I downloaded the binary. OSX complains here, so would be nice to consider signing it. 
![image](https://user-images.githubusercontent.com/5887929/90114497-14d8d480-dd53-11ea-9247-b9ae58e96d79.png)

```
./edgeware-mac --chain=beresheet --name yangwao
```
![image](https://user-images.githubusercontent.com/5887929/90114579-33d76680-dd53-11ea-8617-675a5bc99434.png)

```
Error: Service(Client(Msg("Error parsing embedded file: unknown field `children`, expected `top` or `childrenDefault` at line 8253 column 17")))
````

Any hint?

**Comment by drewstone** [comment]
Ah yes, it is merged with an incorrect spec, you'll have to rename `children` to `childrenDefault` in the `node/cli/res` directory.

**Comment by drewstone** [comment]
Will update the binaries!
