### ISSUE TITLE
account be dropped abnormally

### ISSUE THREAD

**Issue by rayshitou** [hicommonwealth/edgeware-node#239]
Will account be dropped if free balance too low although have many bonded asset?
an example account: https://edgeware.subscan.io/account/isnJkzkss3PGPm6Xb4xNG3EVFshyjZDV6JyqAquMkewabEd

**Comment by renweifeng99** [comment]
Same problem about below account :
https://edgeware.subscan.io/account/o64SYSjiUT52HEZmyLpDqZyXt1H3ZhUmdWLtwV9ncaDt1si

More than 30,000 in staking,but balance is 0,bonded is 0,nonce is 0.

**Comment by ShankarWarang** [comment]
Both of your accounts are migrated now! 🚀

**Comment by renweifeng99** [comment]
**kWdKkDPmcFP4RR9jV2JRzvwDNz2oSXWKh4HqQ1gNnSWpcxN**

Please have a check about above account,thanks for your attention!

**Comment by skymoonca** [comment]
jzyEUWYVWr1iK9TwE66PThA25v54qtaLi5rZLr2HXFv4Eoy

the same problem, more than 13300 balance can't be finded.     please help to check the above account.   thank you very much!

**Comment by ShankarWarang** [comment]
> **kWdKkDPmcFP4RR9jV2JRzvwDNz2oSXWKh4HqQ1gNnSWpcxN**
> 
> Please have a check about above account,thanks for your attention!

> jzyEUWYVWr1iK9TwE66PThA25v54qtaLi5rZLr2HXFv4Eoy
> 
> the same problem, more than 13300 balance can't be finded. please help to check the above account. thank you very much!

Migrated! ⛓

**Comment by skymoonca** [comment]
> > **kWdKkDPmcFP4RR9jV2JRzvwDNz2oSXWKh4HqQ1gNnSWpcxN**
> > Please have a check about above account,thanks for your attention!
> 
> > jzyEUWYVWr1iK9TwE66PThA25v54qtaLi5rZLr2HXFv4Eoy
> > the same problem, more than 13300 balance can't be finded. please help to check the above account. thank you very much!
> 
> Migrated! ⛓

Again!  the below account  did not show  the EDG balance，more than13300，pls help to check. thanksful. 

jzyEUWYVWr1iK9TwE66PThA25v54qtaLi5rZLr2HXFv4Eoy

the same problem, more than 13300 balance can't be finded. please help to check the above account. thank you very much!
