### ISSUE TITLE
3.1.0 build error

### ISSUE THREAD

**Issue by lcgogo** [hicommonwealth/edgeware-node#244]
`     Compiling parity-scale-codec v1.3.5
     Compiling impl-codec v0.4.2
     Compiling sp-storage v2.0.0 (https://github.com/hicommonwealth/substrate.git?branch=develop#86bb8c12)
     Compiling sp-wasm-interface v2.0.0 (https://github.com/hicommonwealth/substrate.git?branch=develop#86bb8c12)
     Compiling sp-tracing v2.0.0 (https://github.com/hicommonwealth/substrate.git?branch=develop#86bb8c12)
     Compiling sp-arithmetic v2.0.0 (https://github.com/hicommonwealth/substrate.git?branch=develop#86bb8c12)
  error[E0282]: type annotations needed
      --> /root/.cargo/git/checkouts/substrate-25d0b09b83fafc89/86bb8c1/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1595 | / implement_fixed!(
  1596 | |     FixedI64,
  1597 | |     test_fixed_i64,
  1598 | |     i64,
  ...    |
  1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
  1602 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error[E0282]: type annotations needed
      --> /root/.cargo/git/checkouts/substrate-25d0b09b83fafc89/86bb8c1/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1604 | / implement_fixed!(
  1605 | |     FixedI128,
  1606 | |     test_fixed_i128,
  1607 | |     i128,
  ...    |
  1611 | |         [-170141183460469231731.687303715884105728, 170141183460469231731.687303715884105727]_",
  1612 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error[E0282]: type annotations needed
      --> /root/.cargo/git/checkouts/substrate-25d0b09b83fafc89/86bb8c1/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1614 | / implement_fixed!(
  1615 | |     FixedU128,
  1616 | |     test_fixed_u128,
  1617 | |     u128,
  ...    |
  1621 | |         [0.000000000000000000, 340282366920938463463.374607431768211455]_",
  1622 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: aborting due to 3 previous errors

  For more information about this error, try `rustc --explain E0282`.
  error: could not compile `sp-arithmetic`

  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
warning: build failed, waiting for other jobs to finish...
error: build failed
The command '/bin/sh -c /edgeware/setup.sh' returned a non-zero code: 101`

**Comment by lcgogo** [comment]
`docker build -t edg:latest .`

**Comment by drewstone** [comment]
Can you try building from source? Also what versions of rust are in your docker env?

**Comment by drewstone** [comment]
Run `rustup override set nightly-2020-08-20-x86_64-apple-darwin` or downgrade to 2020-08-20 on your respective OS. Then rebuild.

**Comment by lcgogo** [comment]
> Run `rustup override set nightly-2020-08-20-x86_64-apple-darwin` or downgrade to 2020-08-20 on your respective OS. Then rebuild.

where to add the config? I add it to scripts/init.sh like below
`
rustup update stable
rustup update nightly
rustup override set nightly-2020-08-20-x86_64-apple-darwin
rustup target add wasm32-unknown-unknown --toolchain nightly
`

But still meet error

**Comment by drewstone** [comment]
Try 2020-10-06, cargo clean, cargo update, cargo build --release
