### ISSUE TITLE
Same problem about below account :

### ISSUE THREAD

**Issue by skymoonca** [hicommonwealth/edgeware-node#245]
Same problem about below account :
https://edgeware.subscan.io/account/o64SYSjiUT52HEZmyLpDqZyXt1H3ZhUmdWLtwV9ncaDt1si

More than 30,000 in staking,but balance is 0,bonded is 0,nonce is 0.

_Originally posted by @renweifeng99 in https://github.com/hicommonwealth/edgeware-node/issues/239#issuecomment-698772831_

**Comment by drewstone** [comment]
All accounts should be migrated now, let us know if you have issues!
