### ISSUE TITLE
Again，account be dropped abnormally

### ISSUE THREAD

**Issue by skymoonca** [hicommonwealth/edgeware-node#247]
Again happened!   the below account did not show the EDG balance，more than13300EDG，please have a check. thank you very much!

jzyEUWYVWr1iK9TwE66PThA25v54qtaLi5rZLr2HXFv4Eoy

**Comment by drewstone** [comment]
All accounts should be migrated now, let us know if you have issues!

**Comment by skymoonca** [comment]
Thanks very much for your reply today，but my account still not show the EDG balance. could you please help to check again.，thanks. 

jzyEUWYVWr1iK9TwE66PThA25v54qtaLi5rZLr2HXFv4Eoy

**Comment by skymoonca** [comment]
OK，thank you.  but I cannot see it in my wallet account. could you send me a link address，how I can get it?

**Comment by drewstone** [comment]
Where are you looking at your wallet balance @skymoonca ?

**Comment by skymoonca** [comment]
In my Mathwallet account，and still now I can't see the balance. could you help me how to get it?  thankyou.
