### ISSUE TITLE
3.1.0 build error

### ISSUE THREAD

**Issue by panchengj** [hicommonwealth/edgeware-node#249]
when i run 'cargo build --release' ,the error below accours:

"
   Compiling syn v1.0.44
error: failed to run custom build command for `edgeware-runtime v3.1.0 (/home/edgeware/edgeware-node/node/runtime)`

Caused by:
  process didn't exit successfully: `/home/edgeware/edgeware-node/target/release/build/edgeware-runtime-e733f8553987d100/build-script-build` (exit code: 1)
  --- stdout
  Executing build command: "rustup" "run" "nightly" "cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/home/edgeware/edgeware-node/target/release/wbuild/edgeware-runtime/Cargo.toml" "--color=always" "--release"

  --- stderr
   Downloading crates ...
    Downloaded fs2 v0.4.3
    Downloaded same-file v1.0.6
    Downloaded serde_json v1.0.59
    Downloaded wasm-gc-api v0.1.11
    Downloaded semver v0.6.0
    Downloaded build-helper v0.1.1
    Downloaded walkdir v2.3.1
    Downloaded substrate-wasm-builder v2.0.1
    Downloaded cargo_metadata v0.10.0
     Compiling wasm-build-runner-impl v1.0.0 (/home/edgeware/edgeware-node/target/release/wbuild-runner/edgeware-runtime7413819723920807445)
      Finished release [optimized] target(s) in 1.81s
       Running `/home/edgeware/edgeware-node/target/release/wbuild-runner/edgeware-runtime7413819723920807445/target/x86_64-unknown-linux-gnu/release/wasm-build-runner-impl`
     Compiling sp-arithmetic v2.0.0 (https://github.com/hicommonwealth/substrate.git?branch=develop#f7ed3c31)
     Compiling finality-grandpa v0.12.3
  error[E0282]: type annotations needed
      --> /home/edgeware/.cargo/git/checkouts/substrate-25d0b09b83fafc89/f7ed3c3/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1595 | / implement_fixed!(
  1596 | |     FixedI64,
  1597 | |     test_fixed_i64,
  1598 | |     i64,
  ...    |
  1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
  1602 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error[E0282]: type annotations needed
      --> /home/edgeware/.cargo/git/checkouts/substrate-25d0b09b83fafc89/f7ed3c3/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1604 | / implement_fixed!(
  1605 | |     FixedI128,
  1606 | |     test_fixed_i128,
  1607 | |     i128,
  ...    |
  1611 | |         [-170141183460469231731.687303715884105728, 170141183460469231731.687303715884105727]_",
  1612 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error[E0282]: type annotations needed
      --> /home/edgeware/.cargo/git/checkouts/substrate-25d0b09b83fafc89/f7ed3c3/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1614 | / implement_fixed!(
  1615 | |     FixedU128,
  1616 | |     test_fixed_u128,
  1617 | |     u128,
  ...    |
  1621 | |         [0.000000000000000000, 340282366920938463463.374607431768211455]_",
  1622 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: aborting due to 3 previous errors

  For more information about this error, try `rustc --explain E0282`.
  error: could not compile `sp-arithmetic`

  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
warning: build failed, waiting for other jobs to finish...
error: build failed
"

how can i fix it?

cargo --version
cargo 1.47.0 (f3c7e066a 2020-08-28)

rustc --version
rustc 1.47.0 (18bf6b4f0 2020-10-07)

**Comment by drewstone** [comment]
Run `rustup override set nightly-2020-08-20-x86_64-apple-darwin` or downgrade to 2020-08-20 on your respective OS. Then rebuild.

**Comment by panchengj** [comment]
I have runed ' rustup override set nightly-2020-08-20 '
                ' rustup target add wasm32-unknown-unknown --toolchain nightly-2020-08-20 '
cargo --version
cargo 1.47.0-nightly (ab32ee88d 2020-08-10)
rustc --version
rustc 1.47.0-nightly (32c654a97 2020-08-19)
rustup --version
rustup 1.22.1 (b01adbbc3 2020-07-08)
rustfmt --version
rustfmt 1.4.20-nightly (48f6c32 2020-08-09)

then i build:  'cargo build --release' ,  it seems ok at first, but errors  accours finally:

"
   Compiling wasmi v0.6.2
error: failed to run custom build command for `wabt-sys v0.8.0`

Caused by:
  process didn't exit successfully: `/root/edgeware-node/target/release/build/wabt-sys-565be438549851d6/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=WABT_CXXSTDLIB
  cargo:rerun-if-env-changed=CXXSTDLIB
  running: "cmake" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.8.0/wabt" "-DBUILD_TESTS=OFF" "-DBUILD_TOOLS=OFF" "-DCMAKE_INSTALL_PREFIX=/root/edgeware-node/target/release/build/wabt-sys-464c1891515f30c6/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  -- The C compiler identification is GNU 5.5.0
  -- The CXX compiler identification is GNU 5.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for alloca.h
  -- Looking for alloca.h - found
  -- Looking for unistd.h
  -- Looking for unistd.h - found
  -- Looking for snprintf
  -- Looking for snprintf - found
  -- Looking for strcasecmp
  -- Looking for strcasecmp - found
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of ssize_t
  -- Check size of ssize_t - done
  -- Check size of size_t
  -- Check size of size_t - done
  -- Found PythonInterp: /usr/bin/python3.5 (found suitable version "3.5.2", minimum required is "3.5") 
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE  
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /root/edgeware-node/target/release/build/wabt-sys-464c1891515f30c6/out/build
  running: "cmake" "--build" "." "--config" "Release" "--"
  Scanning dependencies of target wabt
  [  1%] Building CXX object CMakeFiles/wabt.dir/src/apply-names.cc.o
  [  2%] Building CXX object CMakeFiles/wabt.dir/src/binary.cc.o
  [  3%] Building CXX object CMakeFiles/wabt.dir/src/binary-reader.cc.o
  [  4%] Building CXX object CMakeFiles/wabt.dir/src/binary-reader-ir.cc.o
  [  5%] Building CXX object CMakeFiles/wabt.dir/src/binary-reader-logging.cc.o
  [  6%] Building CXX object CMakeFiles/wabt.dir/src/binary-writer.cc.o
  [  7%] Building CXX object CMakeFiles/wabt.dir/src/binary-writer-spec.cc.o
  [  8%] Building CXX object CMakeFiles/wabt.dir/src/binding-hash.cc.o
  [ 10%] Building CXX object CMakeFiles/wabt.dir/src/color.cc.o
  [ 11%] Building CXX object CMakeFiles/wabt.dir/src/common.cc.o
  [ 12%] Building CXX object CMakeFiles/wabt.dir/src/config.cc.o
  [ 13%] Building CXX object CMakeFiles/wabt.dir/src/decompiler.cc.o
  [ 14%] Building CXX object CMakeFiles/wabt.dir/src/error-formatter.cc.o
  [ 15%] Building CXX object CMakeFiles/wabt.dir/src/expr-visitor.cc.o
  [ 16%] Building CXX object CMakeFiles/wabt.dir/src/feature.cc.o
  [ 17%] Building CXX object CMakeFiles/wabt.dir/src/filenames.cc.o
  [ 19%] Building CXX object CMakeFiles/wabt.dir/src/generate-names.cc.o
  [ 20%] Building CXX object CMakeFiles/wabt.dir/src/hash-util.cc.o
  [ 21%] Building CXX object CMakeFiles/wabt.dir/src/ir.cc.o
  [ 22%] Building CXX object CMakeFiles/wabt.dir/src/ir-util.cc.o
  [ 23%] Building CXX object CMakeFiles/wabt.dir/src/leb128.cc.o
  [ 24%] Building CXX object CMakeFiles/wabt.dir/src/lexer-source.cc.o
  [ 25%] Building CXX object CMakeFiles/wabt.dir/src/lexer-source-line-finder.cc.o
  [ 26%] Building CXX object CMakeFiles/wabt.dir/src/literal.cc.o
  [ 28%] Building CXX object CMakeFiles/wabt.dir/src/opcode.cc.o
  [ 29%] Building C object CMakeFiles/wabt.dir/src/opcode-code-table.c.o
  [ 30%] Building CXX object CMakeFiles/wabt.dir/src/option-parser.cc.o
  CMakeFiles/wabt.dir/build.make:686: recipe for target 'CMakeFiles/wabt.dir/src/option-parser.cc.o' failed
  CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/wabt.dir/all' failed
  Makefile:83: recipe for target 'all' failed

  --- stderr
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS


  /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.8.0/wabt/src/option-parser.cc: In lambda function:
  /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.8.0/wabt/src/option-parser.cc:60:20: error: ‘CMAKE_PROJECT_VERSION’ was not declared in this scope
       printf("%s\n", CMAKE_PROJECT_VERSION);
                      ^
  make[2]: *** [CMakeFiles/wabt.dir/src/option-parser.cc.o] Error 1
  make[1]: *** [CMakeFiles/wabt.dir/all] Error 2
  make: *** [all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 2

  build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.44/src/lib.rs:885:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
"
