### ISSUE TITLE
Change our chainID for EVM network list

### ISSUE THREAD

**Issue by yangwao** [hicommonwealth/edgeware-node#264]
I wanted to add us to https://chainid.network which collects all EVM networks out there... but!
Edgeware has chainID
mainet **7** - https://github.com/yangwao/chains/blob/master/_data/chains/7.json 
testnet Beresheet is **42**. - https://github.com/yangwao/chains/blob/master/_data/chains/42.json

reference https://github.com/paritytech/substrate/blob/78fa1b8062218f1ee5a61c499f433a26ca1783aa/ss58-registry.json#L77 
but Acala put there chainID 595 and 787 https://github.com/ethereum-lists/chains/pull/129/files

Curious if we can adjust and be there?

**Comment by jnaviask** [comment]
This is 2021 now.
