### ISSUE TITLE
Ensure docker works with EVM contract tutorials.

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/edgeware-node#289]
Some users in builders group cannot get it to work, but building from source you can deploy contracts.

**Comment by sascha1337** [comment]
ive been able to deploy using docker-compose and RPC on metamask without issues, but somehow i could not find the contract or data in polka js

**Comment by dillchen** [comment]
@sascha1337 a community member is working on a Blockscout deployment so that you can see what the EVM status looks like!
