### ISSUE TITLE
v3.3.1 - possible error on syncing mainnet from scratch

### ISSUE THREAD

**Issue by JelliedOwl** [hicommonwealth/edgeware-node#315]
Compiled and verified the V3.3.1 node executable with srtool.

On syncing mainnet from scratch I'm getting:

edgeware331[59411]: 2021-06-18 23:51:29 ⚙️  Syncing 347.6 bps, target=#6972447 (25 peers), best: #120737 (0x6099…361f), finalized #119808 (0xfba5…740a), ⬇ 51.4kiB/s ⬆ 18.4kiB/s
edgeware331[59411]: 2021-06-18 23:51:31 Pausing old validator set: Forced change scheduled after inactivity
edgeware331[59411]: 2021-06-18 23:51:33 Pausing old validator set: Forced change scheduled after inactivity
edgeware331[59411]: 2021-06-18 23:51:34 ⚙️  Syncing 311.1 bps, target=#6972448 (25 peers), best: #122293 (0xa71a…15e9), finalized #121856 (0xda4e…e0b4), ⬇ 167.4kiB/s ⬆ 15.7kiB/s
edgeware331[59411]: 2021-06-18 23:51:37 Pausing old validator set: Forced change scheduled after inactivity
edgeware331[59411]: 2021-06-18 23:51:38 Pausing old validator set: Forced change scheduled after inactivity
edgeware331[59411]: 2021-06-18 23:51:39 ⚙️  Syncing 376.8 bps, target=#6972449 (25 peers), best: #124177 (0xae6b…b341), finalized #121856 (0xda4e…e0b4), ⬇ 30.9kiB/s ⬆ 15.4kiB/s
edgeware331[59411]: 2021-06-18 23:51:42 Pausing old validator set: Forced change scheduled after inactivity
edgeware331[59411]: 2021-06-18 23:51:44 Pausing old validator set: Forced change scheduled after inactivity
edgeware331[59411]: 2021-06-18 23:51:44 ⚙️  Syncing 325.6 bps, target=#6972450 (25 peers), best: #125805 (0x9bc0…6f68), finalized #125440 (0x232f…8c00), ⬇ 219.6kiB/s ⬆ 21.9kiB/s

I'm not sure if this is actually an error, or just the logging being a bit noisy while the chain syncs.

**Comment by JelliedOwl** [comment]
Assuming that isn't how this comment from the release manifests (I used the default compilation options).

_If you are syncing from scratch you should not build your node with frontier-block-import as this will cause the node to fail to sync. Instead you should build normally and sync normally. The behavior of your node should not change at all due to this change (in face Wei has told me the frontier block import is a bit useless atm)._

**Comment by drewstone** [comment]
If you’re referring to these “pausing old validator set” logs, these are not errors. This is normal.

**Comment by JelliedOwl** [comment]
I am, so it's a non-issue and I'll close it - thanks.
