### ISSUE TITLE
Fix readme to include all SRML modules

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/edgeware-node#33]
Has treasury been included?

**Comment by jnaviask** [comment]
We depend on and include treasury, but there's currently no way to use it until I build the voting origin.

**Comment by marbar3778** [comment]
is there a reason that all the links for the modules under SRML in readme are using github/com instead of github.com, makes all links break? its on all links so not sure if this is intentional?

**Comment by jnaviask** [comment]
They should be .com. I don't know what happened, but I'll fix it now.

**Comment by jnaviask** [comment]
Fixed here https://github.com/hicommonwealth/edgeware-node/commit/3ee53bc3e33f160309feca7359694878ca21ea08
