### ISSUE TITLE
EDG confirmed block does not increase

### ISSUE THREAD

**Issue by lcgogo** [hicommonwealth/edgeware-node#342]
![图片](https://user-images.githubusercontent.com/8175573/200094489-6ff0e38a-a1a1-4738-be99-4c53f67a3e93.png)

Now the latest block is increasing, the finalized block is hanged at 14210400

**Comment by JelliedOwl** [comment]
We had a short period (8 hours maybe) where not enough of the validators were signing to indicate finality.  This is resolve now and, hopefully, won't re-occur.
