### ISSUE TITLE
Freeze sync

### ISSUE THREAD

**Issue by meltaus** [hicommonwealth/edgeware-node#65]
Sometimes freeze sync blocks
![freeze](https://user-images.githubusercontent.com/13775964/56569918-1b828c00-65e4-11e9-8faa-6389cd5e7d33.png)

**Comment by meltaus** [comment]
![freeze2](https://user-images.githubusercontent.com/13775964/56571720-bdf03e80-65e7-11e9-9221-9bd7d11bb5fc.png)

**Comment by drewstone** [comment]
While there are new reasons for frozen sync, this has been resolved.
