### ISSUE TITLE
purge_chain.sh doesn't delete local_testnet

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/edgeware-node#66]
`purge_chain.sh` currently has a hardcoded list of chains whose data-directories get deleted.

The `--chain=local` testnet gets stored under local_testnet which doesn't get deleted.

Also, have we thought about factoring out the list of possible chains + printing which chains haven't been deleted by purge_chain.sh after it runs?

**Comment by DeepInThought** [comment]
Hi @raykyri,  

I submitted pull request #73 in regards to a completion to this issue.   Let me know if you have any questions.   

Cheers @DeepInThought
