### ISSUE TITLE
Initial Sync is Failing

### ISSUE THREAD

**Issue by joesixpack** [hicommonwealth/edgeware-node#74]
![image](https://user-images.githubusercontent.com/23145642/61296338-c68f8580-a78e-11e9-9a20-fe4069769761.png)

**Comment by drewstone** [comment]
What rust version are you using? Can you spill your stats here? I have no issues syncing on a new node after building from release

`cargo build --release`

**Comment by joesixpack** [comment]
I'm using rust 1.36.0.  I don't think there was an issue with the v0.2.0 release.
