### ISSUE TITLE
Is it possible to make a light weight client of Edgeware chain

### ISSUE THREAD

**Issue by featheryus** [hicommonwealth/edgeware-node#75]
I want to make LWC of Edgeware chain, 
It only need to import enough block head.
Then it can easily verify if a transaction is included in a block.
Is it possible ?

**Comment by drewstone** [comment]
Yes, the client is by default a light client, just run with the flag `--light`.

**Comment by featheryus** [comment]
Thanks
Suppose, I deploy a smart contract and issue a token called coinA, then there is a transaction tx1 (userA transfer 10 coinA to userB), this transaction included in block 100. 
I want to provide the tx1 data , some proof and the block number 100 to light client , it can parse the tx1 and verify tx1 has been finalized in block 100.
