### ISSUE TITLE
No such file or directory, node/service/src/chain_spec.rs:40

### ISSUE THREAD

**Issue by PetoU** [hicommonwealth/edgeware-node#78]
stack backtrace:
   0: backtrace::backtrace::trace::h5cb7804c8a80d753 (0x11059589e)
   1: backtrace::capture::Backtrace::new::h3c86bbf2c4e6eaf9 (0x1105948c8)
   2: substrate_panic_handler::set::{{closure}}::h37f9a1165f1a1219 (0x11054dba1)
   3: std::panicking::rust_panic_with_hook::hddd286a9c773fc67 (0x110675621)
   4: std::panicking::begin_panic::hd721e808771d8e68 (0x10f61da05)
   5: edgeware_service::chain_spec::edgeware_config::h299b7be46c2d110e (0x10fa7feea)
   6: edgeware_cli::load_spec::hb2583dd1fd83b07c (0x10f436e65)
   7: substrate_cli::load_spec::h8c37aec65a0bb427 (0x10f3709c3)
   8: substrate_cli::run_node::h5a09e3c8a228729e (0x10f36d572)
   9: substrate_cli::parse_and_execute::h26b98778597cb645 (0x10f369532)
  10: edgeware_cli::run::h3c68690c7f654d69 (0x10f3d5eba)
  11: edgeware::main::h0a49d424133d37b9 (0x10f310422)
  12: std::rt::lang_start::{{closure}}::hb243eac2d87a3c36 (0x10f28e006)
  13: std::panicking::try::do_call::h8037d9f03e27d896 (0x110674ed8)
  14: __rust_maybe_catch_panic (0x11067dfff)
  15: std::rt::lang_start_internal::hc8e69e673740d4ae (0x1106759be)
  16: main (0x10f3104f9)

Thread 'main' panicked at 'Error opening spec file: No such file or directory (os error 2)', node/service/src/chain_spec.rs:40

*****************************************************************************************

the line in chain_spec.rs 
expects file
 ./testnets/v0.4.0/edgeware.json
which does exists, and contains data.

**Comment by drewstone** [comment]
Make sure you execute the commands from the root directory of the `edgeware-node` repo. Hopefully this helps :).

**Comment by PetoU** [comment]
you're right, I was running from wrong directory

**Comment by soc1c** [comment]
That's horrible UX. Can't you bundle the chainspec?
