### ISSUE TITLE
error: Could not compile `hashmap_core` on Ubuntu 19.04

### ISSUE THREAD

**Issue by AlexanderZaytsev** [hicommonwealth/edgeware-node#89]
Running `cargo build --release` results in the following error:

> error: failed to run custom build command for `edgeware-runtime v0.3.0 (/edgeware/edgeware-node-master/node/runtime)`
> 
> Caused by:
>   process didn't exit successfully: `/edgeware/edgeware-node-master/target/release/build/edgeware-runtime-70a76344fc51e01e/build-script-build` (exit code: 1)
> --- stdout
> Executing build command: "rustup" "run" "nightly" "cargo" "build" "--target=wasm32-unknown-unknown" "--manifest-path=/edgeware/edgeware-node-master/target/release/wbuild/edgeware-runtime/Cargo.toml" "--release"
> 
> --- stderr
>    Compiling wasm-build-runner-impl v1.0.0 (/edgeware/edgeware-node-master/target/release/build/edgeware-runtime-e2b1eed01b4b7ce4/out/wasm_build_runner)
>     Finished release [optimized] target(s) in 0.44s
>      Running `/edgeware/edgeware-node-master/target/release/build/edgeware-runtime-e2b1eed01b4b7ce4/out/wasm_build_runner/target/release/wasm-build-runner-impl`
>    Compiling hashmap_core v0.1.10
> error[E0432]: unresolved import `alloc_crate::collections::CollectionAllocErr`
>   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hashmap_core-0.1.10/src/lib.rs:32:13
>    |
> 32 |     pub use alloc_crate::collections::CollectionAllocErr;
>    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `CollectionAllocErr` in `collections`
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0432`.
> error: Could not compile `hashmap_core`.
> 
> To learn more, run the command again with --verbose.

**Comment by AlexanderZaytsev** [comment]
Same thing happens on a fresh install of Ubuntu 16.04

**Comment by benfen** [comment]
It could be an issue with the current version of the nightly compiler.  You can try to pin the version of nightly to an older version with something like: `rustup default nightly-2019-06-30`.  I haven't bothered trying to search for the specific version where this errors starts happening, but the version I mentioned worked fine for me.

**Comment by pythonpete32** [comment]
@benfen this dosnt work for me. Is this just an ubuntu issue? I have been trying to get it setup for days, I've just tried on ubuntu 19 with 16cores (its painfully slow with anything less) 

What os is this working with

**Comment by benfen** [comment]
I've built it on debian and macOS.  If you use the previous command and the run the `setup.sh` script, the script will cause nightly to update back to tip.  It's best to just run `cargo build --release` right after updating the default.

When I've done it, I just installed a single version of the rust toolchain with: `wget -O - https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly-2019-06-30`.  Either way should work.

**Comment by benfen** [comment]
I've had some problems building when other toolchains are also present.  You can remove those with `rustup toolchain uninstall stable/nightly` or just make sure to rerun the wasm commands once you've set the target (which needs to be done either way):
```
rustup target add wasm32-unknown-unknown --toolchain nightly-2019-06-30
cargo install --git https://github.com/alexcrichton/wasm-gc --force
```
Removing the toolchains is a little bit overkill, but it works and it doesn't seem to hurt anything.
