### ISSUE TITLE
SRML links in readme are all broken

### ISSUE THREAD

**Issue by benfen** [hicommonwealth/edgeware-node#96]
All the SRML links in the readme are in the form `https://github.com/paritytech/hicommonwealth/tree/master/srml/<module>`.  These are all broken.

It's a valid link to either be `https://github.com/paritytech/substrate/tree/master/srml/<module>` or `https://github.com/hicommonwealth/substrate/tree/master/srml/<module>`.  The fix is easy, but I'm not sure if you wanted to link to the parity repo or to your fork, since both organizations are represented in the current URL.

Example:
[Broken link from docs](https://github.com/paritytech/hicommonwealth/tree/master/srml/aura)
[Parity link](https://github.com/paritytech/substrate/tree/master/srml/aura)
[Hicommonwealth link](https://github.com/hicommonwealth/substrate/tree/master/srml/aura)

**Comment by drewstone** [comment]
Thanks I'll get to changing this right away!

**Comment by drewstone** [comment]
Should be fixed @benfen
